### PR TITLE
update outdated link

### PR DESCRIPTION
**Pull request by cybernet**
bootstrap-ie6.min.css

### CODE REVIEW

**Comment by oliverds** [comment]
Actually, that fix was for Bootstrap 2. We need to remove that reference. Thanks!

**Comment by neo22s** [comment]
https://github.com/yclas/yclas/issues/2341

**Comment by cybernet** [comment]
so should i make a PR with that link removed ?

**Comment by neo22s** [comment]
dont worry, thanks a lot we are taking a look to this!

**Pull request closed without merging**
