### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by cybernet**
jQuery 2.2.4 on google cdn
MaPlace 0.2.7
HTML5 tags

### CODE REVIEW

**Comment by cybernet** [comment]
should i close this ?

**Comment by neo22s** [comment]
closed at https://github.com/yclas/yclas/pull/2296

**Comment by cybernet** [comment]
thank you for taking my commits and make them your own. it's not a big deal what i did. just some HTML, but this is not how it's done ...

**Comment by neo22s** [comment]
What you mean? what we did is put it all together into a PR. So my team what did is download your changes in local, test them then group them in a unique PR as it should be. Also all commits need to be related to an issue, it's how we work. We really appreciate the collaboration and your work is here, and theres evidence of it ;)  we appreciate a lot trust me. Love people getting involved. thanks again

**Pull request closed without merging**
